// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0il4o6dZ5PlLc2cBWqN408YeeFYOHDyk',
    appId: '1:389276304056:web:27e8be672dceafe848aa4d',
    messagingSenderId: '389276304056',
    projectId: 'notes-925af',
    authDomain: 'notes-925af.firebaseapp.com',
    storageBucket: 'notes-925af.firebasestorage.app',
    measurementId: 'G-5XSGQ8GP8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxMIdi-TYBNzU68-_M4BZgkt1eflcxroE',
    appId: '1:389276304056:android:c1c098b44c80e9d948aa4d',
    messagingSenderId: '389276304056',
    projectId: 'notes-925af',
    storageBucket: 'notes-925af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHCgMQfrhePZgRPE3WLvIdZIAfNDltrI4',
    appId: '1:389276304056:ios:ca1335469535a37048aa4d',
    messagingSenderId: '389276304056',
    projectId: 'notes-925af',
    storageBucket: 'notes-925af.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHCgMQfrhePZgRPE3WLvIdZIAfNDltrI4',
    appId: '1:389276304056:ios:ca1335469535a37048aa4d',
    messagingSenderId: '389276304056',
    projectId: 'notes-925af',
    storageBucket: 'notes-925af.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0il4o6dZ5PlLc2cBWqN408YeeFYOHDyk',
    appId: '1:389276304056:web:e61ceb5c65e3add948aa4d',
    messagingSenderId: '389276304056',
    projectId: 'notes-925af',
    authDomain: 'notes-925af.firebaseapp.com',
    storageBucket: 'notes-925af.firebasestorage.app',
    measurementId: 'G-K2WXJKVD6F',
  );
}
