// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIE0muClGbzV4Fitsmvo1KjzzY7Gwo7ug',
    appId: '1:606666353884:web:e7c307dda1c23aeecad819',
    messagingSenderId: '606666353884',
    projectId: 'mdpgold-b56ea',
    authDomain: 'mdpgold-b56ea.firebaseapp.com',
    databaseURL: 'https://mdpgold-b56ea-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-b56ea.firebasestorage.app',
    measurementId: 'G-15N1YQ3B4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFAI1bimdiJe6ESb0qwbUzP0nGl9NzzzA',
    appId: '1:606666353884:android:1f03718656b00e61cad819',
    messagingSenderId: '606666353884',
    projectId: 'mdpgold-b56ea',
    databaseURL: 'https://mdpgold-b56ea-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-b56ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkjRReLDIYSLGyGc2M8pKsVR7RJUbzolU',
    appId: '1:606666353884:ios:27f10498a724385fcad819',
    messagingSenderId: '606666353884',
    projectId: 'mdpgold-b56ea',
    databaseURL: 'https://mdpgold-b56ea-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-b56ea.firebasestorage.app',
    iosClientId:
        '606666353884-0bjtmntlc7golhtk1ucec8nq70l7jhnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkjRReLDIYSLGyGc2M8pKsVR7RJUbzolU',
    appId: '1:606666353884:ios:27f10498a724385fcad819',
    messagingSenderId: '606666353884',
    projectId: 'mdpgold-b56ea',
    databaseURL: 'https://mdpgold-b56ea-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-b56ea.firebasestorage.app',
    iosClientId:
        '606666353884-0bjtmntlc7golhtk1ucec8nq70l7jhnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIE0muClGbzV4Fitsmvo1KjzzY7Gwo7ug',
    appId: '1:606666353884:web:f92ce44f4d0a67aacad819',
    messagingSenderId: '606666353884',
    projectId: 'mdpgold-b56ea',
    authDomain: 'mdpgold-b56ea.firebaseapp.com',
    databaseURL: 'https://mdpgold-b56ea-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-b56ea.firebasestorage.app',
    measurementId: 'G-934SE3P4WR',
  );
}
